### ISSUE TITLE
Incluir Ciudades chilenas

### ISSUE THREAD

**Issue by jhonnattan123** [vicasas/dpacl#2]
Es posible encontrar otra subdivisión dentro de las comunas las cuales son las Ciudades. esta información se encuentra Wikipedia pero no logre encontrarla en las paginas oficiales del gobierno.

https://es.wikipedia.org/wiki/Anexo:Ciudades_de_Chile

![image](https://user-images.githubusercontent.com/31730855/99472147-c7a66900-2926-11eb-8ac9-d2dbffc8c56f.png)

creo que seria útil incluir su latitud, longitud, y altura.

**Comment by vicasas** [comment]
@jhonnattan123 ¿Podrías especificar las ciudades que se deberían agregar?. 

Por otro lado si me hace sentido que incluya información de geolocalización como la latitud y longitud y/o altura. Podríamos ver una forma de incluir esta información que sea rescatada con un metodo solo para ese caso en especifico, dado que si queremos hacer una cascada de select de regiones existirá información adicional sin importancia.

**Comment by vicasas** [comment]
@jhonnattan123 podríamos agregar un objeto adicional con la información de la latitud, longitud y altura, algo como `location` o un símil, ahora para la altura no se si debería ser parte de este mismo obj. Si me parece que debería tener un obj de configuración quizás seteado en `false` y que solo si esta en `true` se retorne la data adicional.

**Comment by jhonnattan123** [comment]
> @jhonnattan123 podríamos agregar un objeto adicional con la información de la latitud, longitud y altura, algo como `location` o un símil, ahora para la altura no se si debería ser parte de este mismo obj. Si me parece que debería tener un obj de configuración quizás seteado en `false` y que solo si esta en `true` se retorne la data adicional.

habria que buscar una fuente confiable de informacion y definir el metodo y la estructura del metodo de configuracion.

**Comment by vicasas** [comment]
@jhonnattan123 Exacto, hay que buscar la fuente confiable, de momento cerrare este issue, se debe crear uno especifico para añadir ubicación y altura.
