### ISSUE TITLE
propuesta: agregar métodos para recatar elementos según su id

### ISSUE THREAD

**Issue by jhonnattan123** [vicasas/dpacl#3]
saludos.
en ocasiones uno necesita recatar información de una división territorial en especifico, con los métodos actuales si bien es simple pues es solo rescatar la id. pienso que seria mas cómodo, legible y ordenado si lo incluyéramos como métodos, aparte que así se evitaría hacer una cascada de finds para rescatar datos.

los métodos que propongo de ejemplo son:

```
function getRegionByID(id) {
    return regiones.find((p) => p.id === id);
}

function getProvinciaByID(id) {
    return provincias.find((p) => p.id === id);
}

function getComunaByID(id) {
    return comunas.find((p) => p.id === id);
}
```

**Comment by vicasas** [comment]
@jhonnattan123 No me parece que se deban crear funciones adicionales para recuperar los mismos datos que se pueden recuperar pasándole un parametro `id`. Lo que si podríamos tomar como una mejora el hecho de cambiar los métodos de `filter` que se usan actualmente por `find` si es que es soportado sin transpilar a babel.

**Comment by jhonnattan123** [comment]
> @jhonnattan123 No me parece que se deban crear funciones adicionales para recuperar los mismos datos que se pueden recuperar pasándole un parametro `id`. Lo que si podríamos tomar como una mejora el hecho de cambiar los métodos de `filter` que se usan actualmente por `find` si es que es soportado sin transpilar a babel.

¿o dejarlos como foreachs / for para que sea mas compatible?

**Comment by vicasas** [comment]
@jhonnattan123 Se debe abrir un issue en especifico para ver esta mejora.
