### ISSUE TITLE
propuesta: rama con version cdn de la libreria

### ISSUE THREAD

**Issue by jhonnattan123** [vicasas/dpacl#4]
durante un proyecto realizado sin vue ni react ni ninguna libreria o framework mas que bootstrap, surgio el problema de incluir una version adaptada de esta libreria pero sin un manejador de paquetes. para lo cual se fusionaron las 3 bases de datos en un solo objeto que no fuera modulo, para facilitar su uso en navegadores antiguos, y se dejo toda la libreria en un solo archivo, el cual luego se minifico.
pensaba crear un repositorio aparte con esta solucion pero mejor pense en proponerla aqui para que, quisas, con un comando de npm, en una rama distinta, se pueda realizar este script compilado, y luego exponerlo en CDN para su uso en sistemas que no poseean manejador de paquetes, ya que es muy comun incluir siempre un combo con las divisiones territoriales. tambien quisas incluir un metodo que facilite crear combos que trabajen de la mano para que al cambiar uno se actualice el otro, esto usando javascript nativo.
todo esto en una rama aparte para no hacer mas pesado la libreria actual, y crear codigo basura.
obviamente mencionar esta opcion en la documentacion de la rama principal.

¿que piensan?

**Comment by vicasas** [comment]
@jhonnattan123 Me parece buena idea, dentro del roadmap estaba contemplada la opción de poder disponibilizar una API para recuperar la data, quizás usando Json Server.

**Comment by vicasas** [comment]
@jhonnattan123 Termino dando por cerrado este tema dadoba que no recibi feedback.
